services:
  - type: web
    name: skillbloom-backend
    runtime: node
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://skillbloom-admin:StrongPassword123@cluster0.mongodb.net/skillbloom?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: your_jwt_secret_here
      - key: JWT_EXPIRE
        value: 30d
      - key: PORT
        value: 3000