services:
  - type: web
    name: skillbloom-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd server && npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGO_URI
        value: mongodb+srv://skillbloomadmin:123456skillbloom@cluster0.mongodb.net/skillbloom?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: your_jwt_secret_here
      - key: JWT_EXPIRE
        value: 30d
